calisma3/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from appMy.views import *
from appUser.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',indexPage, name='indexPage'),
    path('netflix',netflix, name='netflix'),  #todo: url de profil id si belli değil
    path('netflix/test', listem, name="listem"),
    path('netflix/<catetitle>', movieType, name="movieType"),
   
    # path('netflixPage<id>',netflixPage, name='netflixPage'),  #todo: url de profil id si belli 
    
    #====USER====#
    path("subscribeUser", subscribeUser, name="subscribeUser"),
    path('profileUser',profileUser, name='profileUser'),
    # path('deleteprofileUser<id>',deleteprofileUser, name='deleteprofileUser'),  #todo: url de profile silme
    path('accountUser',accountUser, name='accountUser'),
    path('loginUser',loginUser, name='loginUser'),
    path('registerUser',registerUser, name='registerUser'),
    path('logoutUser',logoutUser, name='logoutUser'),
    
    
] + static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

appMy/models.py
from django.db import models

class Category(models.Model):
    catetitle=models.CharField(("Kategori"), max_length=50)
    
    def __str__(self):
        return self.catetitle
    
class Type(models.Model):
    type= models.CharField(("Tür"), max_length=50)
    
    def __str__(self):
        return self.type
    
class Card(models.Model):
    category=models.ForeignKey(Category, verbose_name=("Kategori"), on_delete=models.CASCADE)
    type=models.ForeignKey("Type", verbose_name=("Tür"), on_delete=models.CASCADE, null=True)
    title=models.CharField(("Film/dizi"), max_length=50)
    image=models.ImageField(("Resim"), upload_to="image", max_length=200)
    listLike=models.BooleanField(("Listem"), default=False, null=True)
    
    def __str__(self):
        return self.title

appMy/views.py
from django.shortcuts import render,get_object_or_404, redirect
from appUser.models import Profile
from .models import*
from django.contrib.auth.models import User
from appUser.models import Userinfo



def indexPage(request):
    context={}
    
    return render(request, 'index.html', context)


def netflixPage(request , id):  #todo: url de profilin id'sinin gözükmesi 
    profile=get_object_or_404(Profile, id=id)
    context={
        "profile":profile,
    }
    return render(request, 'browse-index.html', context)


def netflix(request):
    profile=Profile.objects.filter(loginp=True, user=request.user).first()
    category=Category.objects.all()
    movieCard = Card.objects.all()
    
    if request.method=="POST":
        cardId=request.POST.get("listLike")
        print("caard:", cardId)
        movieCard = Card.objects.filter(id=int(cardId)).first()
        if movieCard:
            movieCard.listLike =True
            movieCard.save()
        
        return redirect("movieType", movieCard.category.catetitle)
        
    
    context={
        "profile":profile,
        'category':category,
        'movieCard':movieCard
    }
    
   
    return render(request, 'browse-index.html', context)

def listem(request):
    context = {}
    category = Category.objects.all()
    context['category'] = category
    profile=Profile.objects.filter(loginp=True, user=request.user).first()
    context['profile'] = profile  
    card = Card.objects.filter(listLike=True)
    context["cards"] = card
    if request.method=="POST":
        cardId=request.POST.get("unLike")
        print("caard:", cardId)
        movieCard = Card.objects.filter(id=int(cardId)).first()
        if movieCard:
            movieCard.listLike =False
            movieCard.save()
        
    return render(request, 'listem.html', context)



def movieType(request, catetitle=None):
    profile = Profile.objects.filter(loginp=True, user=request.user).first()
    category = Category.objects.all()
    type = Type.objects.all()
    ogeler = {}
    card = None

    for tip in type:
        movies = Card.objects.filter(type=tip,category__catetitle=catetitle)
        if movies.__len__():
            for movie in movies:
                ogeler[tip.type] = movies
                
        
    if catetitle is None:
        card = Card.objects.all()
    else:
        # filmler/diziler opsiyon vs
        card = Card.objects.filter(category__catetitle=catetitle, listLike=True)

    context = {
        "profile": profile,
        "category": category,
        "type_data": type,
        "card": card,
        "catetype" : ogeler.items(),
    }

    return render(request, 'movie-type.html', context)
    
    

  
        
    
    

    

appMy/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Filmler</title>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
     <!-- owl carousel -->
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
     <link rel="stylesheet"
         href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">
        <!-- My CSS -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <style>
        /* MESSAGES START */
        .tost {
            position: fixed;
            top: 20px;
            right: 20px;
            z-index: 2050 !important;
            animation: timeend 5.8s both;
            opacity: 1;

        }

        .time-animate {
            width: 100%;
            height: 10px;
            background: rgba(255, 255, 255, 0.85);
            border-bottom-right-radius: 0.375rem;
            border-bottom-left-radius: 0.375rem;
            overflow: hidden;
        }

        .time-animate div {
            width: 100%;
            height: 100%;
            background: #d59393;
            animation: timew 5s linear both;
        }

        @keyframes timew {
            100% {
                width: 0;
            }
        }

        @keyframes timeend {
            80% {
                opacity: 1;
            }

            100% {
                opacity: 0;
            }
        }

        /* MESSAGES END */
    </style>
    
    {% block css %}
        
    {% endblock css %}
        
</head>

<body>
    {% include 'part/_messages.html' %}

    {% block nonheader %}
    {% include 'part/_header.html' %}
        
    {% endblock nonheader %}
        
    
    {% block main %}
        
    {% endblock main %}
        


    {% include 'part/_footer.html' %}

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>

        <!-- owl carousel script -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>

    
  
  {% block js %}
    
  {% endblock js %}
    
        
</body>

</html>

appMy/templates/browse-index.html
{% extends 'base.html' %}
{% load static %}


{% block css %}
<style>
  /* owl  Carousel*/
  .owl-prev,
  .owl-next {
    display: flex;
    position: absolute;
    transform: scale(4) !important;
    color: red !important;
  }

  .owl-prev {
    top: 70px;
    left: 0;
  }

  .owl-next {
    top: 70px;
    right: 0;
  }

  .owl-prev:hover,
  .owl-next:hover {
    background: none !important;
  }
</style>

{% endblock css %}



{% block main %}
<!-- Hero image -->
<div class="hero-image">

  <div class="hero-text">
    <h1>Sınırsız film, dizi ve çok daha fazlası.</h1>
    <h4>İstediğiniz yerde izleyin. İstediğiniz zaman iptal edin.</h4>
    <p>İzlemeye hazır mısınız? Üyelik oluşturmak veya üyeliğinze erişmek için e-posta adresinizi girin</p>

    <button class="btn btn-secondary btn-lg mt-3">Oynat</button>
    <button class="btn btn-secondary btn-lg mt-3">Daha Fazla Bilgi</button>
  </div>

</div>

<div class="container">
  <div class="row mt-5">



    {% for categoryItem in category %}
    <h3 class="text-light">{{ categoryItem.catetitle }}</h3>


    <div class="galeri owl-carousel owl-theme">
      {% for categoryCard in categoryItem.card_set.all %}
      <div class="item">
        <img src="{{ categoryCard.image.url }}" alt="">
        
      </div>



      {% endfor %}
    </div>


    {% endfor %}



  </div>


</div>

{% endblock main %}

{% block js %}
<script>
  var owl = $('.galeri');
  owl.owlCarousel({
    margin: 10,
    dots: false,
    nav: true,


    smartSpeed: 4000,
    responsive: {
      0: {
        items: 1
      },
      600: {
        items: 3
      },
      1000: {
        items: 4
      }
    }
  })

</script>
{% endblock js %}

appMy/templates/browse.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<style>
    .card img:hover {
        border: 4px solid white;
    }

    button:hover {
        border: 1px solid white;
        color: white !important;
    }
</style>
{% endblock css %}


{% block nonheader %}
<nav class="navbar">
    <div class="container">
        <a href="" class="navbar-brand">
            <img src="{% static 'img/netflix_logo.png' %}" alt="">
        </a>
    </div>
</nav>

<!-- profil seçimi -->
<div class="container">
    <div class="row w-75 m-auto bg-black bg-opacity-25">
        <h1 class="text-center text-light">Kimler İzliyor?</h1>


        {% for i in profile_list %}
        <div class="col-3 mt-5 mb-5" style="position: relative;">
            <div>
                <a href="" class="btn btn-primary" style="position: absolute; z-index: 100;" data-bs-toggle="modal"
                    data-bs-target="#profile{{i.id}}">
                    <i class="bi bi-pencil-square fs-5"></i>
                </a>

                <!-- Modal -->
                <div class="modal fade" id="profile{{i.id}}" tabindex="-1" aria-labelledby="exampleModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog">
                        <form method="POST" enctype="multipart/form-data" class="modal-content"> 
                            {% csrf_token %}
                            <div class="modal-header">
                                <h1 class="modal-title fs-5" id="exampleModalLabel">{{ i.name }} Profili Düzenle</h1>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Close"></button>
                            </div>
                            <div class="modal-body d-flex align-items-center gap-3">
                                <img class="pimage
                                "  style="width: 100px; height: 100px; object-fit: cover; border: 2px solid #00000030;" src="{{ i.image.url }}"
                                    alt="">
                                <div>
                                    <input type="text" name="pname2" value=" {{ i.name }}" class="form-control my-3"
                                        placeholder="Profil Adı">
                                    <input type="file" name="image2" class=" dataimage form-control my-3" onchange="imageChange(this)">
                                    <input type="hidden" value="{{ forloop.counter0 }}">
                                    <input type="hidden"  name="id" value="{{ i.id }}">
                                </div>
                            </div>
                            <div class="modal-footer d-flex justify-content-between">
                                
                                {% comment %}
                                <a href="{% url 'deleteprofileUser' i.id %}" type="submit" class="btn btn-danger">Profili Sil</a>
                                    <P>url de profil silme</P>
                                {% endcomment %}
                                    
                                <button type="submit" name="submit" value="profileDelete" class="btn btn-danger">Profili Sil</button>
                                <div>
                                    <button type="submit" name="submit" value="profileChange" class="btn btn-primary">Düzenle</button>
                                    <button type="button" class="btn btn-secondary"
                                        data-bs-dismiss="modal">İptal</button>

                                </div>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
            <form method="POST" class="d-flex">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{ i.id }}">
                <button type="submit" name="submit" value="profileLogin" class="text-decoration-none text-secondary p-0 border-0 bg-dark">
                    <div class="card bg-transparent">
                        <img src="{{ i.image.url }}" style="height: 200px; object-fit: cover;" class="card-img-top" alt="">
                        <div>
                            <h5 class="card-title text-center ">{{ i.name }}</h5>
                        </div>
                    </div>
                </button>

            </form>
            
            {% comment %}
            <a href="{% url 'netflixPage' i.id %}" class="text-decoration-none text-secondary">
                <div class="card bg-transparent">
                    <img src="{{ i.image.url }}" style="height: 200px; object-fit: cover;" class="card-img-top" alt="">
                    <div>
                        <h5 class="card-title text-center ">{{ i.name }}</h5>
                    </div>
                </div>
            </a>
                
            {% endcomment %}
                
        </div>

        {% endfor %}
        <script>
            let pimage_list = document.querySelectorAll(".pimage");
            let data_list = document.querySelectorAll(".dataimage");

            let imageChange=(e)=>{
                var selectedFile=e.files[0]
                var reader = new FileReader();
                var pindex = e.nextElementSibling.value;

                reader.onload = function(e){
                    pimage_list[pindex].src = e.target.result;
                };
                reader.readAsDataURL(selectedFile)
            }
        </script>




        <div class="buton mb-5 text-center">
            <button class="bg-dark text-secondary w-50 p-2 " data-bs-toggle="modal"
                data-bs-target="#exampleModal">Profil Yönetimi</button>

            <!-- modal -->

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                aria-hidden="true">
                <div class="modal-dialog">
                    <form method="POST" enctype="multipart/form-data" class="modal-content">
                        {% csrf_token %}
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="exampleModalLabel">Profil Ekle</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <div class="modal-body">
                            <input type="text" name="profileName" class="form-control my-3" placeholder="Profil Adı">
                            <input type="file" name="image" class="form-control my-3">
                        </div>
                        <div class="modal-footer">
                            <button type="submit" name="submit" value="profileCreate" class="btn btn-primary">Oluştur</button>
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">İptal</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock nonheader %}

appMy/templates/hesap.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<style>
    body,
    html {
        color: black;
        background-color: beige;
    }

    a {
        text-decoration: none;
    }

    a:hover {
        text-decoration: underline;
    }

    .container {
        margin-top: 100px;
    }

    .accordion,
    .panel {
        background-color: rgba(34, 34, 34, 0);
        color: black;
    }
</style>
{% endblock css %}



{% block main %}
<!-- Hesap -->
<div class="container">
    <div class="row">
        <div class="col">

            <div class="row">
                <h1>Hesap</h1>
                <hr>
                <div class="col">
                    <h4>Üyelik ve Ödemeler</h4>
                    <div>
                        <button  class="btn btn-light border" data-bs-toggle="modal" data-bs-target="#SubscribeModal">Aboneliği İptal et</button>  
                         <!-- Modal -->
                         <div class="modal fade" id="SubscribeModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                         aria-hidden="true">
                         <div class="modal-dialog">
                             <form method="POST" class="modal-content">
                                 {% csrf_token %}
                                 <div class="modal-header">
                                     <h1 class="modal-title fs-5" id="exampleModalLabel">Aboneliğini İptal etmek İstiyor musun?</h1>
                                     <button type="button" class="btn-close" data-bs-dismiss="modal"
                                         aria-label="Close"></button>
                                 </div>
                                 
                                 <div class="modal-footer">
                                    <button type="button" class="btn btn-dark" data-bs-dismiss="modal"
                                    aria-label="Close">Vazgeç</button>
                                     <button type="submit" name="submit" value="subscribeUnfollow" class="btn btn-danger">Aboneliği İptal Et</button>
                                 </div>
                             </form>
                         </div>
                     </div>
                    </div>
                    
                </div>
                <div class="col">
                    <strong>E-Mail:{{request.user.email | slice:":1"}}......{{ request.user.email | slice:"-10:" }}</strong>
                    <p>Parola: {{ request.user.userinfo.password|first }}****{{ request.user.userinfo.password|last }}</p>
                    <p>tel: {{ request.user.userinfo.tel }}</p>
                </div>
                <div class="col">
                    <!-- email -->
                    <div>

                        <a href="" data-bs-toggle="modal" data-bs-target="#EmailModal">E-postayi değiştir</a> <br>
                        <!-- Modal -->
                        <div class="modal fade" id="EmailModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                            aria-hidden="true">
                            <div class="modal-dialog">
                                <form method="POST" class="modal-content">
                                    {% csrf_token %}
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="exampleModalLabel">E-mail Değiştir</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <label for="">Yeni email</label>
                                        <input type="email" name="email" class="form-control">
                                        
                                        <label for="">Şifreyi Giriniz</label>
                                        <input type="password" name="password" id="" class="form-control">
                                    
                                    </div>
                                    <div class="modal-footer">
                                        <button type="submit" name="submit" value="emailUpdate" class="btn btn-primary">Güncelle</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                       
                    </div>
                    <!-- telephone -->
                    <div>

                        <a href="" data-bs-toggle="modal" data-bs-target="#TelModal">Telefon değiştir</a> <br>
                        <!-- Modal -->
                        <div class="modal fade" id="TelModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                            aria-hidden="true">
                            <div class="modal-dialog">
                                <form method="POST" class="modal-content">
                                    {% csrf_token %}
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="exampleModalLabel">Telefon Değiştir</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <label for="">Yeni Telefon</label>
                                        <input type="text" name="tel" class="form-control">
                                        
                                        <label for="">Şifreyi Giriniz</label>
                                        <input type="password" name="password" id="" class="form-control">
                                    
                                    </div>
                                    <div class="modal-footer">
                                        <button type="submit" name="submit" value="telUpdata" class="btn btn-primary">Güncelle</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                       
                    </div>

                    <!-- şifre -->
                    <div>

                        <a href="" data-bs-toggle="modal" data-bs-target="#PasswordModal">Şifre Değiştir</a> <br>
                        <!-- Modal -->
                        <div class="modal fade" id="PasswordModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                            aria-hidden="true">
                            <div class="modal-dialog">
                                <form method="POST" class="modal-content">
                                    {% csrf_token %}
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="exampleModalLabel">Şifre Değiştir</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                            aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <label for="">Eski Şİfreyi Giriniz</label>
                                        <input type="password" name="password" id="" class="form-control">
                                        
                                        <label for="">Yeni Şifre</label>
                                        <input type="password" name="passwordNew" class="form-control">
           
                                        <label for="">Yeni Şifre Tekrar</label>
                                        <input type="password" name="passwordAgain" class="form-control">
                                        
                                    
                                    </div>
                                    <div class="modal-footer">
                                        <button type="submit" name="submit" value="passwordUpdata" class="btn btn-primary">Güncelle</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                       
                    </div>
                </div>
            </div>

            <div class="row">
                <hr>
                <div class="col">
                    <h4>Ayarlar</h4>
                </div>

                <div class="col">
                    <a href="">18+ İçerik</a> <br>
                    <a href="">Teste katılın</a> <br>
                    <a href="">İçerik indirilen cihazları yönet</a>
                </div>
            </div>

            <div class="row">
                <hr>
                <div class="col">
                    <h4>Profil ve ebeveyn kontrolleri</h4>
                </div>

                <div class="col">
                    <button class="accordion"><img src="{% static 'img/smile-profil.png' %}" alt=""> Berkay </button>
                    <div class="panel">
                        <p>
                            <strong>Dil</strong> <br>
                            <a href="" class="text-end">Değiştir</a>
                        </p>
                        <hr>
                        <p>
                            <strong>İzleme Kısıtlamaları</strong> <br>
                            <a href="" class="text-end">Değiştir</a>
                        </p>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

{% endblock main %}

appMy/templates/listem.html
{% extends 'base.html' %}
{% load static %}





{% block css %}
<style>
    /* owl  Carousel*/
.owl-prev, .owl-next{
    display: flex;
    position: absolute;
    transform: scale(4) !important;
    color:red !important;
  }
  
  .owl-prev{
    top: 70px;
    left:0;
  }
  
  .owl-next{
    top: 70px;
    right: 0;
  }
  
  .owl-prev:hover,.owl-next:hover{
   background:none !important;
  }  
  
</style>
    
{% endblock css %}
{% block main %}
<!-- Hero image -->
<div class="hero-image">

    <div class="hero-text">
        <h1>Sınırsız film, dizi ve çok daha fazlası.</h1>
        <h4>İstediğiniz yerde izleyin. İstediğiniz zaman iptal edin.</h4>
        <p>İzlemeye hazır mısınız? Üyelik oluşturmak veya üyeliğinze erişmek için e-posta adresinizi girin</p>

        <button class="btn btn-secondary btn-lg mt-3">Oynat</button>
        <button class="btn btn-secondary btn-lg mt-3">Daha Fazla Bilgi</button>
    </div>

</div>

<div class="container">
    
   
    <div class="row mt-5"> 
      
        <div class="galeri owl-carousel owl-theme">
        
        {% for card in cards %}
            <div class="item">
              <img src="{{ card.image.url }}" alt="">
              <form method="POST">
                {% csrf_token %}
                <input type="hidden" name="unLike" value="{{card.id}}">
                <button class="btn btn-danger" type="submit" name="submit">Unlike</button>
              </form>
             
            </div>
        {% endfor %}
            
              
    </div>
        

        
   
</div>






    


{% endblock main %}




{% block js %}
<script>
  var owl = $('.galeri');
      owl.owlCarousel({
          margin: 10,
          dots:false,
          nav:true,
          
         
          smartSpeed:4000,
          responsive: {
              0: {
                  items: 1
              },
              600: {
                  items: 3
              },
              1000: {
                  items: 4
              }
          }
      })

</script>
{% endblock js %}
    

appMy/templates/login.html
{% extends 'base.html' %}
{% load static %}


{% block css %}
<style>
    h2 {
        text-align: left;
        font-weight: bold;
    }

    .hero-image {
        height: 100%;
    }

    .hero-text {
        background-color: rgba(0, 0, 0, 0.700);
        width: 500px;
        top: 50%;
    }

    .hero-text2 {
        width: 75%;
        margin: auto;
    }

    .form-control {
        background-color: rgb(34, 34, 34);
        border: none;
    }

    .p-grey {
        color: grey;
    }

    .con-footer {
        position: absolute;
        bottom: 0;
        background-color: rgba(0, 0, 0, 0.700);
    }

    @media screen and (max-width: 700px) {
        .hero-image {
            background-image: linear-gradient(rgba(0, 0, 0, 1), rgba(0, 0, 0, 1)), url(img/arkaplan.jpg);
        }
    }
</style>
{% endblock css %}

{% block nonheader %}
<div class="hero-image">
    <!-- navbar -->
    <nav class="navbar">
        <div class="container">
            <a href="" class="navbar-brand"><img src="{% static 'img/netflix_logo.png' %}" alt=""></a>
        </div>
    </nav>

    <div class="hero-text">
        <!-- form -->
        <form method="POST" class="hero-text2 mt-5 mb-5">
            {% csrf_token %}
            <h2>Oturum Aç</h2>

            <div class="mb-3">
                <input type="text" name="username" class="form-control form-control-lg" placeholder="username">
                <input type="password" name="password" id="" class="form-control form-control-lg mt-5">
            </div>
            <div class="d-grid gap-2">
                <button class="btn btn-danger btn-lg" type="submit">Oturum Aç</button>
            </div>

            <div class="form-check text-start">
                <input type="checkbox" name="" id="" class="form-check-input">
                <label for="" class="form-check-label">
                    Beni Hatırla
                </label>
            </div>
            
            {% for i in messages  %}
            <p class="text- danger">{{ i }}</p>
                
            {% endfor %}
                

            <p class="p-grey">
                Netflix'e katılmak ister misiniz? <a href="{% url 'registerUser' %}">Şimdi kaydolun.</a>  <br><br>
                Bu sayfa robot olmadığınızı kanıtlamak için Google reCAPTCHA tarafından korunuyor. Daha fazlasını
                öğrenin.
            </p>
        </form>
    </div>
</div>
{% endblock nonheader %}